{% set name = "tig" %}
{% set version = "2.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jonas/{{ name }}/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: f54f720378c4105a5d3df257e59386b2bd892bd01437f2c5769bd1813300d0b3

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - pkg-config
    - make
  host:
    - pcre
    - ncurses

test:
  commands:
    - tig --version

about:
  home: https://jonas.github.io/tig/
  dev_url: https://github.com/jonas/tig
  summary: Text-mode interface for git
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - wolfv
    - tdejager
    - dbast
