{% set name = "tig" %}
{% set version = "2.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jonas/{{ name }}/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: 5e18e0404d2cb9657e9eff6cdbb2a073fe11449ae8cc0c779be0151fd9d46bdd

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - pkg-config
    - make
  host:
    - pcre
    - ncurses

test:
  commands:
    - tig --version

about:
  home: https://jonas.github.io/tig/
  dev_url: https://github.com/jonas/tig
  summary: Text-mode interface for git
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - wolfv
    - tdejager
    - dbast
